#! /bin/sh

source ~/.config/polybar/scheme

bspc config normal_border_color $black1
bspc config focused_border_color $black2

pgrep -x sxhkd > /dev/null || sxhkd & #keybindings
#/sbin/alsactl init & #sound (moved to xinitrc)
#xled init & #backlighting (moved to xinitrc)
picom --config ~/.config/picom.conf & #compositor
xsetroot -cursor_name left_ptr & #changing cursor
#feh --bg-fill --randomize ~/.backgrounds/static/* & #static wall (random)
sh /home/rhythmrx9/.scripts/set-live.sh & #live wall (random)
#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor -d 一 二 三 四 五 六 七 八 九 #japanese font req.

# rules
bspc rule -a discord desktop='^4' state=tiled follow=false
bspc rule -a qBittorrent desktop='^5' state=tiled follow=true
bspc rule -a vlc desktop='^6' state=tiled follow=true 
bspc rule -a Zathura state=tiled 

# config
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true

#polybar
killall -q polybar
while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done
polybar bar &
